#ifndef PARALLEL_ARRAY_PROCESSING_ARRAY_INITIALIZATION_H
#define PARALLEL_ARRAY_PROCESSING_ARRAY_INITIALIZATION_H

float ** init_array(struct Params params);

#endif //PARALLEL_ARRAY_PROCESSING_ARRAY_INITIALIZATION_H
