#ifndef PARALLEL_ARRAY_PROCESSING_FILE_PROCESSING_H
#define PARALLEL_ARRAY_PROCESSING_FILE_PROCESSING_H

void get_array_from_file(float **arr, FILE *file);

#endif //PARALLEL_ARRAY_PROCESSING_FILE_PROCESSING_H
